import { create } from "zustand";

import { supabase } from "@/lib/supabase";

export type Note = {
  uuid?: number; // int8 primary key, auto-generated by DB
  id: string; // uuid column, gen_random_uuid()
  title: string;
  description: string;
  created_at?: string;
  last_changed?: string;
  ownerId?: string;
};

type NotesState = {
  notes: Note[];
  fetchNotes: () => Promise<void>;
  createNote: (note: Note) => Promise<Note>;
  getNoteById: (id: string) => Note | undefined;
  updateNote: (
    id: string,
    updates: Partial<Pick<Note, "title" | "description">>,
  ) => void;
  saveNote: (
    id: string,
    updates: Partial<Pick<Note, "title" | "description">>,
  ) => Promise<void>;
  deleteNote: (id: string) => Promise<void>;
};

export const useNotesStore = create<NotesState>((set, get) => ({
  notes: [],
  fetchNotes: async () => {
    const { data, error } = await supabase
      .from("notes")
      .select("*")
      .order("created_at", { ascending: false });
    if (error) {
      console.error("Failed to fetch notes:", error.message);
      return;
    }
    set({ notes: data ?? [] });
  },

  createNote: async (note: Note) => {
    const noteWithTimestamp = { ...note, last_changed: new Date().toISOString() };
    set((state) => ({ notes: [noteWithTimestamp, ...state.notes] }));

    const { data, error } = await supabase
      .from("notes")
      .insert({
        id: noteWithTimestamp.id,
        title: noteWithTimestamp.title,
        description: noteWithTimestamp.description,
        last_changed: noteWithTimestamp.last_changed,
        ownerId: (await supabase.auth.getUser()).data.user?.id,
      })
      .select();
    if (error) {
      set((state) => ({
        notes: state.notes.filter((n) => n.id !== note.id),
      }));
      console.error("Failed to insert note:", error.message);
      return null;
    }
    return data[0];
  },
  getNoteById: (id) => get().notes.find((note) => note.id === id),
  updateNote: (id, updates) => {
    // Only updates local state — call saveNote to persist
    set((state) => ({
      notes: state.notes.map((note) =>
        note.id === id ? { ...note, ...updates } : note,
      ),
    }));
  },
  saveNote: async (id, updates) => {
    const updatesWithTimestamp = { ...updates, last_changed: new Date().toISOString() };
    set((state) => ({
      notes: state.notes.map((note) =>
        note.id === id ? { ...note, ...updatesWithTimestamp } : note,
      ),
    }));
    const { error } = await supabase.from("notes").update(updatesWithTimestamp).eq("id", id);
    if (error) {
      console.error("Failed to update note:", error.message);
    }
  },
  deleteNote: async (id) => {
    set((state) => ({ notes: state.notes.filter((n) => n.id !== id) }));
    const { error } = await supabase.from("notes").delete().eq("id", id);
    if (error) {
      console.error("Failed to delete note:", error.message);
    }
  },
}));
